version: "3.9"

services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ticketcontrol-static-data:/vol/web
      - ticketcontrol-uploads:/app/uploads
      - ticketcontrol-settings:/app/settings
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER} # user has to be root with this default config
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - STATIC_URL=/static/static/
      - MEDIA_URL=/static/media/
      - STATIC_ROOT=/vol/web/static/
      - MEDIA_ROOT=/vol/web/media/
    depends_on:
      - db


  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - ticketcontrol-mysql-data:/var/lib/mysql


  proxy:
    build: ./proxy
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 80:8000
    volumes:
      - ticketcontrol-static-data:/vol/static
      - ticketcontrol-uploads:/uploads
    environment:
      - MAX_REQUEST_SIZE=${MAX_REQUEST_SIZE}

volumes:
  ticketcontrol-static-data:
  ticketcontrol-uploads:
  ticketcontrol-settings:
  ticketcontrol-mysql-data:
