version: "3" # 3.9 is too new for playwithdocker

services:
  app:
    image: comet1903/riseupgroup-ticketcontrol-app:latest
    restart: unless-stopped
    volumes:
      - ticketcontrol-static-data:/vol/web
      - ticketcontrol-uploads:/uploads
    environment:
      - DB_HOST=db # can be container name, service name, or real dns / ip
      - DB_NAME=ticketcontrol
      - DB_USER=root # user has to be root with this default config
      - DB_PASS=changeme
      - SECRET_KEY=changeme
      - ALLOWED_HOSTS=*
      - STATIC_URL=/static/static/
      - MEDIA_URL=/static/media/
      - STATIC_ROOT=/vol/web/static/
      - MEDIA_ROOT=/vol/web/media/
    depends_on:
      - db


  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=ticketcontrol
      - MARIADB_ROOT_PASSWORD=changeme
    volumes:
      - ticketcontrol-mariadb-data:/var/lib/mysql


  proxy:
    image: comet1903/riseupgroup-ticketcontrol-proxy:latest
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 80:8000
    volumes:
      - ticketcontrol-static-data:/vol/static
      - ticketcontrol-uploads:/uploads
    environment:
      - MAX_REQUEST_SIZE=20M

volumes:
  ticketcontrol-static-data:
  ticketcontrol-uploads:
  ticketcontrol-mariadb-data:
