version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - ticketcontrol-static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER} # user has to be root with this default config
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - STATIC_URL=/static/static/
      - MEDIA_URL=/static/media/
      - STATIC_ROOT=/vol/web/static/
      - MEDIA_ROOT=/vol/web/media/
    depends_on:
      - db
  db:
    image: mariadb:10.6
    restart: always
    volumes:
      - ticketcontrol-mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
    volumes:
      - ticketcontrol-static-data:/vol/static
    environment:
      - MAX_REQUEST_SIZE=${MAX_REQUEST_SIZE}

volumes:
  ticketcontrol-static-data:
  ticketcontrol-mariadb-data:
