version: "3.9"

services:
  app:
    build: .
    restart: unless-stopped
    command: >
      sh -c "
        while ! python manage.py sqlflush > /dev/null 2>&1; do
          echo 'Waiting for the db to be ready.';
          sleep 1;
        done;
      
        python manage.py migrate && 
        ls -d ticketcontrol/fixtures/* | xargs python manage.py loaddata &&
        python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db # can be container name, service name, or real dns / ip
      - DB_NAME=ticketcontrol
      - DB_USER=root # user has to be root with this default config
      - DB_PASS=changeme
      - EMAIL_HOST=smtp.ionos.de
      - EMAIL_PORT=465
      - EMAIL_TLS=true
      - EMAIL_SSL=false
      - EMAIL_ADDRESS=noreply@riseupgroup.net
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SECRET_KEY=changeme
      - ALLOWED_HOSTS=*
      - DEBUG=1
      - STATIC_URL=/static/static/
      - MEDIA_URL=/static/media/
      - STATIC_ROOT=/vol/web/static/
      - MEDIA_ROOT=/vol/web/media/
    ports:
      - 8000:8000
    volumes:
      - ./app:/app # auto refresh server files
      - ./data/web:/vol/web
    depends_on: # make serve name as dns work & connect containers
      - db


  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=ticketcontrol
      - MARIADB_ROOT_PASSWORD=changeme
    ports:
      - 3306:3306
