# Generated by Django 4.0.3 on 2022-03-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ticketcontrol', '0002_alter_ticket_moderator_alter_ticket_participating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='moderator',
            field=models.ManyToManyField(blank=True, related_name='moderator', to='ticketcontrol.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='participating',
            field=models.ManyToManyField(blank=True, to='ticketcontrol.user'),
        ),
    ]
