# Generated by Django 4.0.3 on 2022-03-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketcontrol', '0003_alter_ticket_moderator_alter_ticket_participating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketcontrol.user'),
            preserve_default=False,
        ),
    ]
