# Generated by Django 4.0.3 on 2022-03-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketcontrol', '0004_remove_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('change_user_permission', 'Change the permissions of other users'),)},
        ),
    ]
