# Generated by Django 4.0.3 on 2022-03-15 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ticketcontrol', '0006_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ticketcontrol.user'),
            preserve_default=False,
        ),
    ]
