# Generated by Django 4.0.3 on 2022-04-05 18:51

# Changes default values of Ticket.status

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketcontrol', '0007_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned'), ('Closed', 'Closed'), ('Open', 'Open'), ('Waiting', 'Waiting')], default='Unassigned', max_length=15),
        ),
    ]
