# Generated by Django 4.0.4 on 2022-04-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketcontrol', '0008_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('change_user_permission', 'Change the permissions of other users'), ('admin_general', 'Allow access to the Admin Panel'))},
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
