# Generated by Django 4.0.4 on 2022-04-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketcontrol', '0011_alter_user_options_user_email_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
