# Generated by Django 4.0.4 on 2022-05-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketcontrol', '0012_user_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
