# Generated by Django 4.0.4 on 2022-05-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketcontrol', '0014_alter_ticket_options_ticket_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': (('hide_ticket', 'Hide the Ticket to everyone (shown as delete in the ui)'), ('unhide_ticket', 'Recover the Ticket (shown as recover ticket in the ui)'), ('change_ticket_status', 'Change Ticket status'), ('assign_ticket', 'Assign Ticket to users'))},
        ),
    ]
