# Generated by Django 4.0.5 on 2022-06-11 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketcontrol', '0016_remove_ticket_moderator_ticket_moderators'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': (('hide_ticket', 'Hide the Ticket to everyone'), ('unhide_ticket', 'Recover the Ticket'), ('change_ticket_status', 'Change Ticket status'), ('assign_ticket', 'Assign Ticket to users'))},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderating', to='ticketcontrol.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='ticketcontrol.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='participating',
            field=models.ManyToManyField(blank=True, related_name='participating', to='ticketcontrol.user'),
        ),
    ]
