# Generated by Django 4.0.6 on 2022-07-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ticketcontrol', '0019_rename_creationdate_attachment_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='auth.group'),
        ),
    ]
