# Generated by Django 4.0.3 on 2022-03-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='moderator',
            field=models.ManyToManyField(null=True, related_name='moderator', to='ticketcontrol.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='participating',
            field=models.ManyToManyField(null=True, to='ticketcontrol.user'),
        ),
    ]
